# --- Defaults ---

# --- pymarl options ---
runner: "episode" # Runs 1 env for an episode
mac: "basic_mac" # Basic controller
env: "pred_prey" # Environment name
env_args: {} # Arguments for the environment
batch_size_run: 1 # Number of environments to run in parallel
test_nepisode: 20 # Number of episodes to test for
test_interval: 2000 # Test after {} timesteps have passed
test_greedy: True # Use greedy evaluation (if False, will set epsilon floor to 0
log_interval: 2000 # Log summary of stats after every {} timesteps
runner_log_interval: 2000 # Log runner stats (not test stats) every {} timesteps
learner_log_interval: 2000 # Log training stats every {} timesteps
t_max: 10000 # Stop running after this many timesteps
use_cuda: True # Use gpu by default unless it isn't available
use_buffer_compression: False
buffer_device: ~
buffer_algo: ~
buffer_chunk_size: ~


# --- EA options ---
# Only frac (mutation alpha) and state_alpha (beta for VMM) need to be adjusted
EA: 0
rl_to_ea_synch_period: 1
pop_size: 5
elite_fraction: 0.2 # default setting
mutation_prob: 0.9 # default setting
prob_reset_and_sup: 0.05 # default setting
frac: 1.0 # mutation alpha, see paper for details
pr_dim: 64  # default setting
EA_alpha: 1.0  # default setting
Org_alpha: 1.0 # default setting
N_type: 1 # default setting
SAME: 0  # default setting
start_timesteps: 10000
EA_freq : 1  # default setting
state_alpha: 0.1   # beta control VMM, see paper for details

# --- Logging options ---
use_tensorboard: False # Log results to tensorboard
save_model: False # Save the models to disk
save_model_interval: 100000 # Save models after this many timesteps
checkpoint_path: "" # Load a checkpoint from this path
evaluate: False # Evaluate model for test_nepisode episodes and quit (no training)
load_step: 0 # Load model trained on this many timesteps (0 if choose max possible)
save_replay: False # Saving the replay of the model loaded from checkpoint_path
local_results_path: "results" # Path for local results

# --- RL hyperparameters ---
gamma: 0.99
batch_size: 32 # Number of episodes to train on
buffer_size: 32 # Size of the replay buffer
lr: 0.0005 # Learning rate for agents
critic_lr: 0.0005 # Learning rate for critics
recurrent_critic: False
optim_alpha: 0.99 # RMSProp alpha
optim_eps: 0.00001
grad_norm_clip: 10 # Reduce magnitude of gradients above this L2 norm

# --- Agent parameters ---
agent: "rnn" # Default rnn agent
rnn_hidden_dim: 64 # Size of hidden state for default rnn agent
obs_agent_id: True # Include the agent's one_hot id in the observation
obs_last_action: True # Include the agent's last action (one_hot) in the observation

# --- Experiment running params ---
repeat_id: 1
label: "default_label"
run_mode: "sequential"
n_runners: 1
continuous_actions: False
debug: False
buffer_mode: "transitions"
n_train: 1
learn_interval: 100
testing_on: True
buffer_cpu_only: True
runner_scope: episodic
plot_loss_network: False
verbose: False
optimizer: rmsprop
target_update_mode: hard