# --- COVDN specific parameters ---
action_range: ~
action_selector: ~
agent: cemrnn
obs_agent_id: True # Include the agent's one_hot id in the observation
obs_last_action: True # Include the agent's last action (one_hot) in the observation
agent_output_type: "q"
batch_size_run: 1
batch_size: 32
buffer_size: 5000
buffer_warmup: 0
critic_lr: ~
double_q: False
epsilon_decay_mode: ~
epsilon_start: ~
epsilon_finish: ~
epsilon_anneal_time: ~
exploration_mode: "gaussian"
start_steps: 0 # Number of steps for uniform-random action selection, before running real policy. Helps exploration.
act_noise: 0.1 # Stddev for Gaussian exploration noise added to policy at training time.
ou_theta: 0.15 # D
ou_sigma: 0.2 # D
ou_noise_scale: 0.3
final_ou_noise_scale: 0.
gamma: 0.85
grad_norm_clip: 0.5
learner: "cq_learner"
lr: 0.01
mac: cqmix_mac
mixer: "vdn"
name: "covdn_pp"
n_runners: ~
n_train: 1
optimizer: adam # D
optimizer_epsilon: 0.01 # D
ou_stop_episode: 100 # training noise goes to zero after this episode
rnn_hidden_dim: 64
run_mode: ~
runner: "episode"
runner_scope: 'episodic'
target_update_interval: 200 # update the target network every {} episodes
target_update_mode: 'soft'
target_update_tau: 0.001
test_greedy: True
test_interval: 2000
test_nepisode: 10
testing_on: True
t_max: 2000000
save_model: False
save_model_interval: 10000
verbose: False
weight_decay: True
weight_decay_factor: 0.0001